export enum REDUCER_ACTIONS_MOVIES {
  SET_ERROR = "SET_ERROR",
  SET_LOADING = "SET_LOADING",
  SET_MOVIES = "SET_MOVIES",
  SET_CURRENT_PAGE = "SET_CURRENT_PAGE",
  ADD_TOP_FAVORITE_MOVIE = "ADD_TOP_FAVORITE_MOVIE", 
  DELETE_TOP_FAVORITE_MOVIE = "DELETE_TOP_FAVORITE_MOVIE", 
}

export enum SAGA_ACTIONS_MOVIES {
  FETCH_MOVIES = "FETCH_MOVIES",
}